const catalogo = [];export const videojuegos_nintendo = [
  // --- NINTENDO DS ---
  {
    id: 1,
    nombre: "New Super Mario Bros.",
    Plataforma: "Nintendo DS",
    Categoria: "Plataformas",
    Precio: 25,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 8,
  },
  {
    id: 2,
    nombre: "Pokémon Edición Platino",
    Plataforma: "Nintendo DS",
    Categoria: "RPG",
    Precio: 75,
    Estado_Conservacion: "solo-cartucho",
    stock: 3,
  },
  {
    id: 3,
    nombre: "Mario Kart DS",
    Plataforma: "Nintendo DS",
    Categoria: "Carreras",
    Precio: 20,
    Estado_Conservacion: "usado-caja-danada",
    stock: 6,
  },
  {
    id: 4,
    nombre: "The Legend of Zelda: Phantom Hourglass",
    Plataforma: "Nintendo DS",
    Categoria: "Aventura",
    Precio: 35,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 4,
  },
  {
    id: 5,
    nombre: "El Profesor Layton y la Villa Curiosa",
    Plataforma: "Nintendo DS",
    Categoria: "Puzles",
    Precio: 20,
    Estado_Conservacion: "nuevo-precintado",
    stock: 5,
  },

  // --- NINTENDO 3DS ---
  {
    id: 6,
    nombre: "Super Mario 3D Land",
    Plataforma: "Nintendo 3DS",
    Categoria: "Plataformas",
    Precio: 25,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 7,
  },
  {
    id: 7,
    nombre: "The Legend of Zelda: A Link Between Worlds",
    Plataforma: "Nintendo 3DS",
    Categoria: "Aventura",
    Precio: 35,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 4,
  },
  {
    id: 8,
    nombre: "Pokémon Sol",
    Plataforma: "Nintendo 3DS",
    Categoria: "RPG",
    Precio: 30,
    Estado_Conservacion: "solo-cartucho",
    stock: 5,
  },
  {
    id: 9,
    nombre: "Fire Emblem: Awakening",
    Plataforma: "Nintendo 3DS",
    Categoria: "RPG",
    Precio: 45,
    Estado_Conservacion: "usado-caja-danada",
    stock: 2,
  },
  {
    id: 10,
    nombre: "Animal Crossing: New Leaf",
    Plataforma: "Nintendo 3DS",
    Categoria: "Simulación",
    Precio: 30,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 6,
  },

  // --- NINTENDO WII ---
  {
    id: 11,
    nombre: "Super Mario Galaxy",
    Plataforma: "Nintendo Wii",
    Categoria: "Plataformas",
    Precio: 35,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 5,
  },
  {
    id: 12,
    nombre: "Mario Kart Wii",
    Plataforma: "Nintendo Wii",
    Categoria: "Carreras",
    Precio: 30,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 9,
  },
  {
    id: 13,
    nombre: "The Legend of Zelda: Skyward Sword",
    Plataforma: "Nintendo Wii",
    Categoria: "Aventura",
    Precio: 40,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 3,
  },
  {
    id: 14,
    nombre: "Super Smash Bros. Brawl",
    Plataforma: "Nintendo Wii",
    Categoria: "Lucha",
    Precio: 25,
    Estado_Conservacion: "usado-caja-danada",
    stock: 4,
  },
  {
    id: 15,
    nombre: "Wii Sports",
    Plataforma: "Nintendo Wii",
    Categoria: "Deportes",
    Precio: 15,
    Estado_Conservacion: "solo-disco",
    stock: 12,
  },
  {
    id: 16,
    nombre: "Donkey Kong Country Returns",
    Plataforma: "Nintendo Wii",
    Categoria: "Plataformas",
    Precio: 25,
    Estado_Conservacion: "nuevo-precintado",
    stock: 3,
  },
  {
    id: 17,
    nombre: "Metroid Prime 3: Corruption",
    Plataforma: "Nintendo Wii",
    Categoria: "Aventura",
    Precio: 30,
    Estado_Conservacion: "usado-como-nuevo",
    stock: 2,
  },
];