export const catalogo = [
  // --- NINTENDO DS ---
  {
    id: 1,
    nombre: "New Super Mario Bros.",
    plataforma: "Nintendo DS",
    categoria: "Plataformas",
    precio: 25,
    estado: "usado-como-nuevo",
    stock: 8,
  },
  {
    id: 2,
    nombre: "Pokémon Edición Platino",
    plataforma: "Nintendo DS",
    categoria: "RPG",
    precio: 75,
    estado: "solo-cartucho",
    stock: 3,
  },
  {
    id: 3,
    nombre: "Mario Kart DS",
    plataforma: "Nintendo DS",
    categoria: "Carreras",
    precio: 20,
    estado: "usado-caja-danada",
    stock: 6,
  },
  {
    id: 4,
    nombre: "The Legend of Zelda: Phantom Hourglass",
    plataforma: "Nintendo DS",
    categoria: "Aventura",
    precio: 35,
    estado: "usado-como-nuevo",
    stock: 4,
  },
  {
    id: 5,
    nombre: "El Profesor Layton y la Villa Curiosa",
    plataforma: "Nintendo DS",
    categoria: "Puzles",
    precio: 20,
    estado: "nuevo-precintado",
    stock: 5,
  },

  // --- NINTENDO 3DS ---
  {
    id: 6,
    nombre: "Super Mario 3D Land",
    plataforma: "Nintendo 3DS",
    categoria: "Plataformas",
    precio: 25,
    estado: "usado-como-nuevo",
    stock: 7,
  },
  {
    id: 7,
    nombre: "The Legend of Zelda: A Link Between Worlds",
    plataforma: "Nintendo 3DS",
    categoria: "Aventura",
    precio: 35,
    estado: "usado-como-nuevo",
    stock: 4,
  },
  {
    id: 8,
    nombre: "Pokémon Sol",
    plataforma: "Nintendo 3DS",
    categoria: "RPG",
    precio: 30,
    estado: "solo-cartucho",
    stock: 5,
  },
  {
    id: 9,
    nombre: "Fire Emblem: Awakening",
    plataforma: "Nintendo 3DS",
    categoria: "RPG",
    precio: 45,
    estado: "usado-caja-danada",
    stock: 2,
  },
  {
    id: 10,
    nombre: "Animal Crossing: New Leaf",
    plataforma: "Nintendo 3DS",
    categoria: "Simulación",
    precio: 30,
    estado: "usado-como-nuevo",
    stock: 6,
  },

  // --- NINTENDO WII ---
  {
    id: 11,
    nombre: "Super Mario Galaxy",
    plataforma: "Nintendo Wii",
    categoria: "Plataformas",
    precio: 35,
    estado: "usado-como-nuevo",
    stock: 5,
  },
  {
    id: 12,
    nombre: "Mario Kart Wii",
    plataforma: "Nintendo Wii",
    categoria: "Carreras",
    precio: 30,
    estado: "usado-como-nuevo",
    stock: 9,
  },
  {
    id: 13,
    nombre: "The Legend of Zelda: Skyward Sword",
    plataforma: "Nintendo Wii",
    categoria: "Aventura",
    precio: 40,
    estado: "usado-como-nuevo",
    stock: 3,
  },
  {
    id: 14,
    nombre: "Super Smash Bros. Brawl",
    plataforma: "Nintendo Wii",
    categoria: "Lucha",
    precio: 25,
    estado: "usado-caja-danada",
    stock: 4,
  },
  {
    id: 15,
    nombre: "Wii Sports",
    plataforma: "Nintendo Wii",
    categoria: "Deportes",
    precio: 15,
    estado: "solo-disco",
    stock: 12,
  },
  {
    id: 16,
    nombre: "Donkey Kong Country Returns",
    plataforma: "Nintendo Wii",
    categoria: "Plataformas",
    precio: 25,
    estado: "nuevo-precintado",
    stock: 3,
  },
  {
    id: 17,
    nombre: "Metroid Prime 3: Corruption",
    plataforma: "Nintendo Wii",
    categoria: "Aventura",
    precio: 30,
    estado: "usado-como-nuevo",
    stock: 2,
  },
  {
    "id": 18,
    "titulo": "Chrono Trigger",
    "plataforma": "SNES",
    "categoria": "RPG",
    "precioBase": 45,
    "estado": "usado-como-nuevo",
    "stock": 4
  },
  {
    "id": 19,
    "titulo": "Streets of Rage 2",
    "plataforma": "MEGA DRIVE",
    "categoria": "Lucha",
    "precioBase": 60,
    "estado": "nuevo-precintado",
    "stock": 10
  }
];